TCC_ALCINDO NETO/TCC_ALCINDO/TCC_ALCINDO/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using TCC_ALCINDO.Models;


namespace TCC_ALCINDO.Controllers
{
    [Authorize]
    public class AnimalController : BaseController
    {
        private readonly AnimalDAO _animalDAL;

        public AnimalController()
        {
            _animalDAL = new AnimalDAO();
        }

        public ActionResult Index(string pesquisa)
        {
            List<Animal> list = _animalDAL.Listar(pesquisa);

            return View(list);
        }

        public ActionResult Detalhes(int id = 0)
        {
            if (id == 0)
                return RedirectToAction("Index");

            Animal animal = _animalDAL.Buscar(id);

            return View(_animalDAL.Buscar(id));
        }

        public ActionResult Cadastro()
        {
            var animal = new Animal(SessionUser.Id);

            return View(animal);
        }

        public ActionResult Editar(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }

            try
            {
                var obj = _animalDAL.Buscar(id);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possível buscar o animal. {0}", ex.Message);
                return View();
            }
        }


        public ActionResult Salvar(Animal obj,int idCliente, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                
                if (upload != null && upload.ContentLength > 0)
                    using (var reader = new BinaryReader(upload.InputStream))
                    {
                        obj.Foto = reader.ReadBytes(upload.ContentLength);
                    }

                try
                {
                    obj.Cliente = new Cliente()
                    {
                        Id = idCliente
                    };

                    _animalDAL.Salvar(obj);
                    TempData["SuccessMsg"] = "Animal salvo com sucesso!";

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    TempData["ErrorMsg"] = string.Format("Falha ao salvar animal. {0}", ex.Message);
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(obj.Id == 0 ? "Cadastro" : "Editar", obj);
            }
        }


        public ActionResult Excluir(int id)
        {
            try
            {
                //var usuario = (Usuario)Session["usuario"];
                _animalDAL.Delete(new Animal(SessionUser.Id) { Id = id });//, usuario);
                TempData["SuccessMsg"] = "Animal excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao excluir animal. {0}", ex.Message);
            }
            return RedirectToAction("Index");
        }

        public ActionResult VisualizarAnimal(int id)
        {
            Animal animal = _animalDAL.Buscar(id);

            return File(animal.Foto, "image/jpg");
        }
    }
}

TCC_ALCINDO NETO/TCC_ALCINDO/TCC_ALCINDO/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCC_ALCINDO.Models;

namespace TCC_ALCINDO.Controllers
{
    public class ClienteController : BaseController
    {
        public ActionResult Index(string pesquisa)
        {
            try
            {
                var lst = new ClienteDAO().Listar(pesquisa);
                return View(lst);
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao buscar clientes. {0}", ex.Message);
                return View(new List<Cliente>());
            }
        }
        public ActionResult Cadastro()
        {
            return View();
        }
        public ActionResult Editar(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }

            try
            {
                var obj = new ClienteDAO().Buscar(id);
                obj.Animais = new AnimalDAO().Listar(obj);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possível buscar o cliente. {0}", ex.Message);
                return View();
            }

        }
        public ActionResult Salvar(Cliente obj)
        {
            if (!obj.IsCpf())
                ModelState.AddModelError("CPF", "CPF inválido");

            if (!ModelState.IsValid)
                return View("Cadastro", obj);

            try
            {
                //var cliente = (Cliente)Session["cliente"];
                new ClienteDAO().Salvar(obj);//, cliente);
                TempData["SuccessMsg"] = "Cliente salvo com sucesso!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = string.Format("Não foi possível buscar o cliente. {0}", ex.Message);

            }
            return RedirectToAction("Editar", new { @id = obj.Id });
        }

        public ActionResult Excluir(int id)
        {
            try
            {
                //var usuario = (Usuario)Session["usuario"];
                new ClienteDAO().Delete(new Cliente { Id = id });//, usuario);
                TempData["SuccessMsg"] = "Cliente excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao excluir cliente. {0}", ex.Message);
            }
            return RedirectToAction("Index");
        }

    }
}

TCC_ALCINDO NETO/TCC_ALCINDO/TCC_ALCINDO/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCC_ALCINDO.Models;

namespace TCC_ALCINDO.Controllers
{
    public class ProdutoController : BaseController
    {
        //
        // GET: /Produto/

        public ActionResult Index(string pesquisa)
        {
            try
            {
                var lst = new ProdutoDAO().Listar(pesquisa);
                return View(lst);
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao buscar clientes. {0}", ex.Message);
                return View(new List<Produto>());
            }
        }

        public ActionResult Cadastro()
        {
            return View();

        }

        public ActionResult Editar(int id = 0)
        {
            if (id == 0)
            {
                return View();
            }


            try
            {
                var obj = new ProdutoDAO().Buscar(id);
                return View(obj);
            }
            catch (KeyNotFoundException ex)
            {
                TempData["ErrorMsg"] = ex.Message;
                return View();
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Não foi possível buscar o item. {0}", ex.Message);
                return View();
            }

        }

        public ActionResult Salvar(Produto obj)
        {

            if (!ModelState.IsValid)
                return View("Cadastro", obj);

            try
            {
                //var usuario = (Usuario)Session["usuario"];
                new ProdutoDAO().Salvar(obj);//, usuario);
                TempData["SuccessMsg"] = "Item salvo com sucesso!";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = string.Format("Não foi possível buscar o item. {0}", ex.Message);

            }
            return View("Editar", obj);
        }

        public ActionResult Excluir(int id)
        {
            try
            {
                //var usuario = (Usuario)Session["usuario"];
                new ProdutoDAO().Delete(new Produto { Id = id });//, usuario);
                TempData["SuccessMsg"] = "Item excluído com sucesso.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMsg"] = String.Format("Falha ao excluir item. {0}", ex.Message);
            }
            return RedirectToAction("Index");
        }

    }
}

TCC_ALCINDO NETO/TCC_ALCINDO/TCC_ALCINDO/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TCC </title>
    @Styles.Render("~/Content/bootstrap.min.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse ">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Abrir Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Cliente")">TCC</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Animal <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Novo", "Cadastro", "Animal")</li>
                            <li>@Html.ActionLink("Visualizar todos", "Index", "Animal")</li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produto <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Novo", "Cadastro", "Produto")</li>
                            <li>@Html.ActionLink("Visualizar todos", "Index", "Produto")</li>
                        </ul>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" action="@Url.Action("Index", "Cliente")">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Buscar cliente..." name="pesquisa">
                    </div>
                    <button type="submit" class="btn btn-default">Buscar</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    @if (((TCC_ALCINDO.Models.Cliente)Session["Usuario"]) != null)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Minha conta <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Visualizar", "Account")">Visualizar perfil</a></li>
                                <li><a href="@Url.Action("AlterarSenha", "Account")">Alterar senha</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("LogOff", "Account")">Sair</a></li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Cadastrar", "Account")"><span class="glyphicon glyphicon-user">Cadastrar</span></a>
                            <a href="@Url.Action("Login", "Account")"><span class="glyphicon glyphicon-log-in">Login</span></a>
                        </li>
                    }
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - TCC Alcindo Neto - Contato com o Pet-Shop: Telefone (XX) XXXX-XXXX E-mail: exemplo@mail.com </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

TCC_ALCINDO NETO/TCC_ALCINDO/TCC_ALCINDO/Views/Shared/_LayoutOLD.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>